#! Experiment Meta Data:
meta:
  name: 'RNA_seq_test'
  design: "input_design.txt"
  

# fastqc configuration
fastqc:
  # Flag to indicate whether fastqc should be run or not
  run: True

# cudaAdapt configuration
cudaAdapt:
  # Flag to indicate whether cudaAdapt should be run or not
  run: True
  # Adapter sequence for read1
  adapter_a: 'AGATCGGAAGAG'
  # Adapter sequence for read2
  adapter_A: 'AGATCGGAAGAG'
  # Number of CPU cores to use for cudaAdapt
  cpu_cores: '2'
  # Threshold quality score to trim
  quality_score_threshold : '20'
  # Threshold minimum length of read to keep
  min_length_threshold: '50'

# trimmed_fastqc configuration
trimmed_fastqc:
  # Flag to indicate whether trimmed_fastqc should be run or not
  run: True

# starIndex configuration
starIndex:
  # Flag to indicate whether starIndex should be run or not
  run: True
  # Path to the gtf file for starIndex
  gtf_path: '/RNAseq/resources/genome.gtf'
  # Path to the reference fasta file for starIndex
  ref_path: '/RNAseq/resources/genome.fasta'
  # Number of CPU cores to use for starIndex
  cpu_cores: '2'
  # Read overhang value for starIndex
  overhang: '150'
  # RAM limit for starIndex
  genome_ram_limit: '35000000000'

# starMapping configuration
starMapping:
  # Number of CPU cores to use for starMapping
  cpu_cores: '2'
  # RAM limit for BAM sorting during starMapping
  limitBAMsortRAM : '120416916151'
  # Run mode for starMapping
  runMode: 'alignReads'
  # Command to read files for starMapping
  readFilesCommand: 'zcat'
  # OutSAM strand field for starMapping
  outSAMstrandField: 'intronMotif'
  # Quantization modes for starMapping
  quantMode : ['GeneCounts', 'TranscriptomeSAM' ]
  # OutSAM type for starMapping
  outSAMtype : 'BAM'

# qualiMap configuration
qualiMap:
  # Flag to indicate whether qualiMap should be run or not
  run: True
  # Memory size for qualiMap
  mem-size: '8'

DeSeq2:
  p_value: '0.05'
  ref: 'Control'
