fastqc:
  run: True

cudaAdapt:
  run: True
  adapter_a: 'AATCCCGGATAGG'
  adapter_A: 'AATTCCGGATAGG'
  cpu_cores: '4'
  quality_score_threshold : '20'
  min_length_threshold: '50'

trimmed_fastqc:
  run: True

 
starIndex:
  # path to gtf file
  run: True
  gtf_path: 'path/to/genome.gtf'
  ref_path: 'path/to/genome.fa'

qualiMap:
  mem-size: '8'





