cudaAdapt:
  first_adapter: 'AATCCCGGATAGG'
  second_adapter: 'AATTCCGGATAGG'

starIndex:
  # path to gtf file
  gtf: 'path/to/genome.gtf'
  ref: 'path/to/genome.fa'
  genome: 'hg38'

cudaAdapt:
  run: True


